spring:
  datasource:
    username: root
    #username: admin
    password: 123456
    url: jdbc:mysql://47.110.139.219:3306/mws?serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/tbextension?serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的fileters,去掉后监控界面sql无法统计,'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobaDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  executor-type: batch

